name: Publish

on:
  pull_request:
    branches: [ "production" ]
    types:
      - closed

jobs:
  Merged:

    strategy:
      matrix:
        java-version: [ 22 ]

    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set headless property
        run: echo "JAVA_OPTS=-Djava.awt.headless=true" >> $GITHUB_ENV

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.java-version }}-

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build the application
        run: mvn package

      - name: Get current version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION="$VERSION.${{ github.run_number }}"
          echo "0.0.VERSION=$VERSION" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "target/**.jar"
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
