name: Testing

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        java-version: [22]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set headless property
        run: echo "JAVA_OPTS=-Djava.awt.headless=true" >> $GITHUB_ENV

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.java-version }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ matrix.java-version }}-

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Download and unzip PMD
        run: |
          curl -OL https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0/pmd-dist-7.0.0-bin.zip
          unzip pmd-dist-7.0.0-bin.zip
          alias pmd="$HOME/pmd-bin-7.0.0/bin/pmd"

      - name: Run PMD
        run: |
          pmd check -d src/main/java -R rulesets/java/quickstart.xml -f html > pmd_report.html

      - name: Generate Jacoco report
        run: mvn jacoco:report

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      - name: Upload PMD Report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: pmd_report.html
